# Generated by Django 5.2.12 on 2026-03-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='file_names',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='operation',
            name='total_file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
